########################################## MNIST ############################################################
configurations = \
{0: [{'base_model_name': "WAE",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 10000,
      'num_last_epoch_fid_samples': 10000},  # Use None of 0 to avoid FID computation
                                           {'expt_name': 'WAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 3e-2,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 9.39
                                            'n_components': 10},],

 1: [{'base_model_name': "std_vae",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'VAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.312,  # = 0.0195*16,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM FID 17.66, N(0, 1) FID: 19.21
                                            'constant_sigma': None,
                                            'n_components': 10},],

 2: [{'base_model_name': "std_vae",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'CV-VAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.0195*2,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet 10 FID is : 17.87, one gaussian fit FID is 33.79
                                            'constant_sigma': 0.7,
                                            'n_components': 10},],

 3: [{'base_model_name': "RAE",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},
                                            {'expt_name': 'RAE-GP',
                                             'num_filters': 128,
                                             'recon_loss_type': 'l2',
                                             'spec_norm_on_dec_only': False,
                                             'model_name': 'MNIST',
                                             'bottleneck_factor': 16,
                                             'gen_reg_type': ['grad_pen'],
                                             'gen_reg_weight': [0.5e-7],
                                             'embedding_weight': 1e-4,
                                             'pretrained_mdl_path': None,
                                             'include_batch_norm': True,  # GMM_Dirichlet FID is : 11.54
                                             'n_components': 10},],

 4: [{'base_model_name': "RAE",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 10000,
      'num_last_epoch_fid_samples': 10000},  # Use None of 0 to avoid FID computation
                                           {'expt_name': 'RAE-L2',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [1e-7],
                                            'embedding_weight': 1e-4,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 8.69
                                            'n_components': 10},],

 5: [{'base_model_name': "RAE",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 100000,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'RAE-SN',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['spec_norm'],
                                            'gen_reg_weight': [None],
                                            'embedding_weight': 0.009,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 11.74
                                            'n_components': 10},],

 6: [{'base_model_name': "RAE",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 10000,
      'num_last_epoch_fid_samples': 10000},  # Use None of 0 to avoid FID computation
                                           {'expt_name': 'RAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.5e-3,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 9.81
                                            'n_components': 10},],

 7: [{'base_model_name': "RAE",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 10000,
      'num_last_epoch_fid_samples': 10000},  # Use None of 0 to avoid FID computation
                                           {'expt_name': 'AE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 10.66
                                            'n_components': 10},],
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++ MNIST FINISHED ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

########################################################## CIFAR_10 #################################################################
 8: [{'base_model_name': "WAE",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'WAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CIFAR',
                                            'bottleneck_factor': 128,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.006,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM FID: 93.53
                                            'n_components': 10},],

 9: [{'base_model_name': "std_vae",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'VAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CIFAR',
                                            'bottleneck_factor': 128,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'constant_sigma': None,
                                            'embedding_weight': 0.024,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # N(0, I) FID: 106
                                            'n_components': 10},],

10: [{'base_model_name': "std_vae",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},
                                          {'expt_name': 'CV-VAE',
                                           'recon_loss_type': 'l2',
                                           'spec_norm_on_dec_only': False,
                                           'model_name': 'CIFAR',
                                           'kernel_size': None,
                                           'num_filters': 128,
                                           'bottleneck_factor': 128,
                                           'gen_reg_type': ['l2'],
                                           'gen_reg_weight': [0],
                                           'embedding_weight': 9e-4,
                                           'cycle_emb_loss_weight': None,
                                           'pretrained_mdl_path': None,
                                           'include_batch_norm': True,  # GMM FID: 86.64
                                           'n_components': 10,
                                           'constant_sigma': 0.7},],

11: [{'base_model_name': "RAE",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},
                                          {'expt_name': 'RAE-GP',
                                           'recon_loss_type': 'l2',
                                           'spec_norm_on_dec_only': False,
                                           'model_name': 'CIFAR',
                                           'kernel_size': None,
                                           'num_filters': 128,
                                           'bottleneck_factor': 128,
                                           'gen_reg_type': ['grad_pen'],
                                           'gen_reg_weight': [0],
                                           'embedding_weight': 9e-4,
                                           'cycle_emb_loss_weight': None,
                                           'pretrained_mdl_path': None,
                                           'include_batch_norm': True,
                                           'n_components': 10,
                                           'constant_sigma': 0.7},],

12: [{'base_model_name': "RAE",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},  # Use None of 0 to avoid FID computation
                                           {'expt_name': 'RAE-L2',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CIFAR',
                                            'bottleneck_factor': 128,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [1e-6],
                                            'embedding_weight': 1e-3,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM FID: 74
					    'n_components': 10},],

13: [{'base_model_name': "RAE",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'RAE-SN',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CIFAR',
                                            'bottleneck_factor': 128,
                                            'gen_reg_type': ['spec_norm'],
                                            'gen_reg_weight': [None],
                                            'embedding_weight': 0.03,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM FID: 75.30
					    'n_components': 10},],

14: [{'base_model_name': "RAE",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},  # Use None of 0 to avoid FID computation
                                           {'expt_name': 'RAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CIFAR',
                                            'bottleneck_factor': 128,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 1e-2,
                                            'pretrained_mdl_path': None,  # GMM FID: 76.28
                                            'include_batch_norm': True,
					                        'n_components': 10},],

15: [{'base_model_name': "RAE",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},  # Use None of 0 to avoid FID computation
                                           {'expt_name': 'AE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CIFAR',
                                            'bottleneck_factor': 128,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM FID: 76.47
					                        'n_components': 10},],
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++ CIFAR_10 FINISHED +++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

######################################################## CELEBA #####################################################################
16: [{'base_model_name': "WAE",
      'dataset_name': "CELEBA",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'WAE',
                                            'recon_loss_type': None,
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'kernel_size': 5,
                                            'num_filters': 128,
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 100,
                                            'cycle_emb_loss_weight': None,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,
                                            'n_components': 10},],

17: [{'base_model_name': "std_vae",
      'dataset_name': "CELEBA",
      'batch_size': 1000,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 10000,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'VAE',
                                            'recon_loss_type': 'l2',
                                            'num_filters': 128,
                                            'spec_norm_on_dec_only': None,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['grad_pen'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.09024,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,
                                            'constant_sigma': None,  # FID of random samples are : 48.305703961984136
                                            'n_components': 10},],

18: [{'base_model_name': "std_vae",
      'dataset_name': "CELEBA",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 100,
      'num_last_epoch_fid_samples': 10000},

                                           {'expt_name': 'CV-VAE',
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'kernel_size': None,
                                            'num_filters': 64,
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.01,
                                            'cycle_emb_loss_weight': None,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,
                                            'n_components': 1,
                                            'constant_sigma' : 0.7,},],

19: [{'base_model_name': "RAE",
      'dataset_name': "CELEBA",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},

                                           {'expt_name': 'RAE-GP',
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'kernel_size': None,
                                            'num_filters': 128,
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['grad_pen'],
                                            'gen_reg_weight': [1e-7],
                                            'embedding_weight': 1e-4,
                                            'cycle_emb_loss_weight': None,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet 10 FID is : 45.63,
                                            'n_components': 10},],

20: [{'base_model_name': "RAE",
      'dataset_name': "CELEBA",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},

                                           {'expt_name': 'RAE-L2',
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'kernel_size': None,
                                            'num_filters': 128,
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [1e-7],
                                            'embedding_weight': 1e-4,
                                            'cycle_emb_loss_weight': None,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,
                                            'n_components': 10},],

21: [{'base_model_name': "RAE",
      'dataset_name': "CELEBA",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},

                                           {'expt_name': 'RAE-SN',
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'kernel_size': None,
                                            'num_filters': 128,
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['spec_norm'],
                                            'gen_reg_weight': [None],
                                            'embedding_weight': 2.4e-3,
                                            'cycle_emb_loss_weight': None,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 40.95
                                            'n_components': 10},],

22: [{'base_model_name': "RAE",
      'dataset_name': "CELEBA",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},

                                           {'expt_name': 'RAE',
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'kernel_size': None,
                                            'num_filters': 128,
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 1e-4,
                                            'cycle_emb_loss_weight': None,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 44.68
                                            'n_components': 10},],

23: [{'base_model_name': "RAE",
      'dataset_name': "CELEBA",
      'batch_size': 100,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},

                                           {'expt_name': 'AE',
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'kernel_size': None,
                                            'num_filters': 128,
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0,
                                            'cycle_emb_loss_weight': None,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM_Dirichlet FID is : 45.10
                                            'n_components': 10},],
#++++++++++++++++++++++++++++++++++++++++++++++ CELEBA FINISHED +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

################################################## AE with L2 decoder regularization #################################################
 24: [{'base_model_name': "RAE",
       'dataset_name': "MNIST",
       'batch_size': 100,
       'epochs': 100,
       'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
       'log_fid_with_smpls': 10000, # Use None of 0 to avoid FID computation
       'num_last_epoch_fid_samples': 10000},
                                            {'expt_name': 'AE-l2',
                                             'num_filters': 128,
                                             'recon_loss_type': 'l2',
                                             'spec_norm_on_dec_only': False,
                                             'model_name': 'MNIST',
                                             'bottleneck_factor': 16,
                                             'gen_reg_type': ['l2'],
                                             'gen_reg_weight': [1e-7],
                                             'embedding_weight': 0,
                                             'pretrained_mdl_path': None,
                                             'include_batch_norm': True,
                                             'constant_sigma': None,
                                             'second_stage_beta' : None,
                                             'n_components': 10},],

 25: [{'base_model_name': "RAE",
       'dataset_name': "CIFAR_10",
       'batch_size': 100,
       'epochs': 100,
       'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
       'log_fid_with_smpls': 0,
       'num_last_epoch_fid_samples': 10000},
                                            {'expt_name': 'AE-l2',
                                             'num_filters': 128,
                                             'recon_loss_type': 'l2',
                                             'spec_norm_on_dec_only': False,
                                             'model_name': 'CIFAR',
                                             'bottleneck_factor': 128,
                                             'gen_reg_type': ['l2'],
                                             'gen_reg_weight': [1e-6],
                                             'embedding_weight': 0,
                                             'pretrained_mdl_path': None,
                                             'include_batch_norm': True,
                                             'constant_sigma': None,
                                             'second_stage_beta' : None,
                                             'n_components': 10},],

 26: [{'base_model_name': "RAE",
       'dataset_name': "CELEBA",
       'batch_size': 100,
       'epochs': 100,
       'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
       'log_fid_with_smpls': 0,
       'num_last_epoch_fid_samples': 10000},
                                            {'expt_name': 'AE-l2',
                                             'num_filters': 128,
                                             'recon_loss_type': 'l2',
                                             'spec_norm_on_dec_only': False,
                                             'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                             'kernel_size': 5,
                                             'bottleneck_factor': 64,
                                             'gen_reg_type': ['l2'],
                                             'gen_reg_weight': [1e-6],
                                             'embedding_weight': 0,
                                             'pretrained_mdl_path': None,
                                             'include_batch_norm': True,
                                             'constant_sigma': None,
                                             'second_stage_beta' : None,
                                             'n_components': 10},],
#+++++++++++++++++++++++++++++++++++++++++++++++++AE with L2 decoder regularization Finished ++++++++++++++++++++++++++++++++++++++++#

################################################## 2D MNIST ##########################################################################
 27: [{'base_model_name': "std_vae",
       'dataset_name': "MNIST",
       'batch_size': 100,
       'epochs': 100,
       'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
       'log_fid_with_smpls': 0,
       'num_last_epoch_fid_samples': 10000},

                                            {'expt_name': 'VAE',
                                             'num_filters': 128,
                                             'recon_loss_type': 'l2',
                                             'spec_norm_on_dec_only': False,
                                             'model_name': 'MNIST',
                                             'bottleneck_factor': 2,
                                             'gen_reg_type': ['l2'],
                                             'gen_reg_weight': [0],
                                             'embedding_weight': 0.312/(2**5), # = 0.0195*16,
                                             'pretrained_mdl_path': None,
                                             'include_batch_norm': True,  # GMM FID 17.66, N(0, 1) FID: 19.21
                                             'constant_sigma': None,
                                             'n_components': 10},],
#+++++++++++++++++++++++++++++++++++++++++++++++++ 2D MNIST FINISHED +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

################################################### 2Stage VAES ######################################################################
28: [{'base_model_name': "std_vae",
      'dataset_name': "CELEBA",
      'batch_size': 1000,
      'epochs': 70,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 10000,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'VAE',
                                            'recon_loss_type': 'l2',
                                            'num_filters': 128,
                                            'spec_norm_on_dec_only': None,
                                            'model_name': 'CELEBA_WAE_PAPER_MAN_EMB_SZIE',
                                            'bottleneck_factor': 64,
                                            'gen_reg_type': ['grad_pen'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.09024,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,
                                            'constant_sigma': None,  # FID of random samples are : 48.305703961984136
                                            'second_stage_beta': 2.0*1e-3,
                                            'n_components': 10},],

 29: [{'base_model_name': "std_vae",
      'dataset_name': "CIFAR_10",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 1000,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'VAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'CIFAR',
                                            'bottleneck_factor': 128,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'constant_sigma': None,
                                            'embedding_weight': 0.024,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # N(0, I) FID: 106
                                            'second_stage_beta': 1*1e-3,
                                            'n_components': 10},],

 30: [{'base_model_name': "std_vae",
      'dataset_name': "MNIST",
      'batch_size': 100,
      'epochs': 100,
      'log_root':  '/is/cluster/work/pghosh/high_res_vae/logs',
      'log_fid_with_smpls': 0,
      'num_last_epoch_fid_samples': 10000},
                                           {'expt_name': 'VAE',
                                            'num_filters': 128,
                                            'recon_loss_type': 'l2',
                                            'spec_norm_on_dec_only': False,
                                            'model_name': 'MNIST',
                                            'bottleneck_factor': 16,
                                            'gen_reg_type': ['l2'],
                                            'gen_reg_weight': [0],
                                            'embedding_weight': 0.312,  # = 0.0195*16,
                                            'pretrained_mdl_path': None,
                                            'include_batch_norm': True,  # GMM FID 17.66, N(0, 1) FID: 19.21
                                            'constant_sigma': None,
                                            'second_stage_beta': 1.5*1e-3,
                                            'n_components': 10},],
#++++++++++++++++++++++++++++++++++++++++++++++++++ 2Stage VAEs +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
}